name: MinewebBridge
main: fr.vmarchaud.mineweb.bukkit.BukkitCore
version: 4.0.0
api-version: 1.15
authors:
  - ThisIsMac
  - Shyrogan
  - Holo795
  - Sytorex
softdepend:
  - ProtocolLib
load: STARTUP
commands:
  mineweb:
    description: Commands to manage MineWebBridge
    usage: |
      Use /help mineweb [subcommand] for more information
      /mineweb reset - Reset the link
      /mineweb port <port> - Setup custom port
      /mineweb bot <token> - Setup bot token
  mineweb reset:
    description: Reset plugin configuration
    usage: /mineweb reset
    permission: mineweb.reset
  mineweb port:
    description: Setup custom port
    usage: /mineweb port <port>
    permission: mineweb.port
#  mineweb bot:
#    description: Setup discord bot token
#    usage: /mineweb bot <token>
#    permission: mineweb.bot